import './components/_video';
import './components/_fancy';
import './components/_scrollToSection';
import './components/_menu-toggle';
import './components/_form-validation';
import './components/_form-submit';
import './components/_prevent-click';
import './components/_closeModal';
import './components/_mask';
